# Generated by Django 3.2.2 on 2021-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210518_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='b_attachment',
            field=models.FileField(blank=True, null=True, upload_to='base/attachments/'),
        ),
        migrations.AddField(
            model_name='bug',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to='base/images/'),
        ),
    ]
