# Generated by Django 3.2.2 on 2021-05-27 14:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210527_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
